### PR TITLE
Added support for low and high temperatures in the current weather

### PR DESCRIPTION
**Pull request by tobiaghiraldini**

### CODE REVIEW

**Comment by comyarzaheri** [comment]
Very cool! This looks good to me overall. Would you mind also adding low/high temperature to the unit test method `testTransformResponseCurrent` in OpenWeatherMapTests.m? After that I'll merge the change. Thanks for the contribution!

**Comment by tobiaghiraldini** [comment]
Oh, sorry for forgetting to include tests in my implementation. I'll update the tests and i'll commit it asap.
It could be also useful to update the other apis with the whole data returned by the openweathermap response.
I'll take care of it, opening issues for each upgrade i'll be working on.

**Comment by tobiaghiraldini** [comment]
Updated unit tests

**Comment by comyarzaheri** [comment]
It looks like one of the tests is failing. This is the output from Travis CI:

```
/Users/travis/build/comyarzaheri/CZWeatherKit/CZWeatherKit Tests/CZOpenWeatherMapTests.m:191: ((50.2339) equal to (weatherData.current.lowTemperature.f) +/- (epsilon)) failed: ("50.2339") is not equal to ("65.276588") +/- ("0.001000"):
188     XCTAssertEqualObjects(@"Clear", weatherData.current.summary);
189     XCTAssertEqualWithAccuracy(65.2765, weatherData.current.temperature.f, epsilon);
190     XCTAssertEqualWithAccuracy(18.4869, weatherData.current.temperature.c, epsilon);
```

**Comment by tobiaghiraldini** [comment]
Can you please help me figuring out where to take those temperature values that I should put in tests? I just took them from other requests tests, but reading the travis error looks like it expects different values.
Being a current request, I am not quite sure if it's possibile to provide with a valid low and high temperature values that remain valid for future test runs

**Comment by tobiaghiraldini** [comment]
Ok, I figured it out. Didn't see the json for the request stub.
I'll update it as well and re-submit

**Comment by tobiaghiraldini** [comment]
Updated tests

**Comment by comyarzaheri** [comment]
Alright, everything looks good. Merged!

**Pull request merged**
